### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by XayOn** [finereli/termenu#4]
"version" does not work on python3.

**Comment by gooli** [comment]
Apparently a lot of things don't work on Python 3, haven't tried it in a long time.
I'll port the library when I have some free time. Any chance you can help me with that?

Also, out of curiosity, what are you using termenu for?

**Comment by finereli** [comment]
Have been running it under Python 3 for a long time now. Not sure it works on Python 2 anymore, but closing this one.
